accounts/urls.py
from django.urls import path
from .views import SignUpView


app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import BlogListView,DetailViewPage, BlogCreateView,BlogUpdateView,BlogDeleteView

app_name ='blog'

urlpatterns = [
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', DetailViewPage.as_view(), name='post_detail'),
    path('', BlogListView.as_view(),name='home'),
]   

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include

from blog.views import BlogListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('blog.urls')),
    path('', BlogListView.as_view(),name='home'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.shortcuts import redirect, reverse
from django.db import models
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    author =models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})
    
    

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'blog/signup.html'

blog/views.py
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from .models import Post


class BlogListView(ListView):
    model = Post
    template_name ='blog/home.html'
    context_object_name = 'object_list'
    
    
class DetailViewPage(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name ='individual_post'
    
    
    
class BlogCreateView(CreateView):
    template_name = 'blog/post_new.html'
    model = Post
            
    fields = ['title', 'author', 'content']
    
    
            
    
class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'content']
    
class BlogDeleteView(DeleteView):
    model = Post
    template_name='blog/post_delete.html'
    success_url = reverse_lazy('blog:home')

blog/templates/blog/base.html
{% comment %} templates/base.html {% endcomment %}

{% load static %}


<html>
    <head>
        <title>MyWebsite</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel ="stylesheet">
        <link href="{% static 'css/base.css' %}" rel =" stylesheet">
    </head>
    <body>
        <div>
            <header>
                <div class="nav-left">
                    <h1><a href ="{% url 'blog:home' %}">WorldWide Goods Solution</a></h1>
                </div>
                <div class="nav-right">
                    <a href="{% url 'blog:post_new' %}">+ New Blog Post </a>
                </div>

            </header>
            {% if user.is_authenticated %}
                <p>Hi {{user.username}}!</p>
                <p><a href="{% url 'logout' %}">Log out</p>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}


{% block content %}
    {% for post in object_list %}
        <div class="post-entry">
            <h2><a href ="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.content }}</p>
        </div>
    {% endfor %}
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Delete Post</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{object.title}}"?</p>

        <input type ="submit" value="Confirm" />
    </form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="post-entry">
        <h2>{{ object.title }}</h2>
        <p>{{ object.content }}</p>
    </div>

    <a href ="{% url 'blog:post_edit'  object.pk %}"> +Edit Blog Post</a>
    <a href ="{% url 'blog:post_delete'  object.pk %}"> +Delete Blog Post</a>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Edit Post</h1>
    <form action="" method="post">{% csrf_token %}
        {{form.as_p}}
    <input type ="submit" value="Update" />
    </form>

{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/base.html" %}

{% block content %}
    <h1> New Post</h1>
    <form action="" method="post">{% csrf_token %}
        {{form.as_p}}
        <input type ="submit" value= "save" />
    </form>
{% endblock content %}

blog/templates/blog/signup.html
{% extends "blog/base.html" %}

{% block content %}
    <h2>Sign Up</h2>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Sign Up</button>
    </form>
{% endblock content %}